/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./src/components/Buttons/Buttons.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElButtonGroups: typeof import('element-plus/es')['ElButtonGroups']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColumn: typeof import('element-plus/es')['ElColumn']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProvide: typeof import('element-plus/es')['ElProvide']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    Error: typeof import('./src/components/Error.vue')['default']
    'Ic:baselineHome': typeof import('~icons/ic/baseline-home')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    'IconIc:baselineHome': typeof import('~icons/ic/baseline-home')['default']
    'IconIcons8:chevronDownRound': typeof import('~icons/icons8/chevron-down-round')['default']
    'Icons8:chevronDownRound': typeof import('~icons/icons8/chevron-down-round')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTable: typeof import('./src/components/ScrollTable.vue')['default']
    TableScrollButs: typeof import('./src/components/TableScrollButs.vue')['default']
  }
}
